title: <p align="center"> David Hudson </p>

logo: "https://github.com/davidhudson88/davidhudson88.github.io/blob/main/Images/rsz_1linkedinprofile2.jpg?raw=true"

description:
  <p align="center">
  <a href="https://github.com/davidhudson88/davidhudson88.github.io/blob/main/PDF/Hudson%2CDavid_Resume2022.pdf">Resume</a> 
  <a href="https://www.linkedin.com/in/davidbhudson/">LinkedIn</a> |
  <a href="https://vrfy.digital/TChSV" >Data Science Certificate</a> 
  </p>
  
  <p align="justify">  
  Data Science and Economics enthusiast with a MSc Degree in Quantitative Economics  and certified in Data Science.
  <br><br>
  Currently looking for new employment opportunities to put my skills to use solving business and social needs.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
