title: <p align="center"> David Hudson </p>

logo: "https://github.com/davidhudson88/davidhudson88.github.io/blob/main/Images/rsz_1linkedinprofile2.jpg?raw=true"

description:
  <p align="center">
  <a href="https://github.com/davidhudson88/davidhudson88.github.io/blob/main/PDF/Hudson%2CDavid_Resume2022.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidbhudson/">LinkedIn</a> |
  <a href="https://vrfy.digital/TChSV" >DS Certificate</a> 
  </p>
  
  <p align="justify">  
  I am a EMPI Engineer at Novant Health and a Data Science and Economics enthusiast.
  <br><br>
  I am passionate about using my skills to solving business and social needs.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
